### ISSUE TITLE
Upload or add links to slides

### ISSUE THREAD

**Issue by annakrystalli** [tobyhodges/building-communities#1]
Hey @tobyhodges, @stelfrich & @led02

I've added a link to my slides in the README. It'd be helpful for the blogpost if I could have access to everyone else's too if possible (no need for @StephanJanosch though 😁). Either adding to the repo or adding a url would work.

 🙏

**Comment by tobyhodges** [comment]
Hey @annakrystalli! Done, for Stefan and me.

**Comment by annakrystalli** [comment]
Thanks all! I have all slides now. Working on this today.
